// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: pb/moo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Moo_Login_FullMethodName = "/pb.Moo/Login"
)

// MooClient is the client API for Moo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MooClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type mooClient struct {
	cc grpc.ClientConnInterface
}

func NewMooClient(cc grpc.ClientConnInterface) MooClient {
	return &mooClient{cc}
}

func (c *mooClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Moo_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MooServer is the server API for Moo service.
// All implementations must embed UnimplementedMooServer
// for forward compatibility
type MooServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedMooServer()
}

// UnimplementedMooServer must be embedded to have forward compatible implementations.
type UnimplementedMooServer struct {
}

func (UnimplementedMooServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMooServer) mustEmbedUnimplementedMooServer() {}

// UnsafeMooServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MooServer will
// result in compilation errors.
type UnsafeMooServer interface {
	mustEmbedUnimplementedMooServer()
}

func RegisterMooServer(s grpc.ServiceRegistrar, srv MooServer) {
	s.RegisterService(&Moo_ServiceDesc, srv)
}

func _Moo_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MooServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Moo_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MooServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Moo_ServiceDesc is the grpc.ServiceDesc for Moo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Moo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Moo",
	HandlerType: (*MooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Moo_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/moo.proto",
}
